smoketest

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -164,7 +164,7 @@ jobs:
           name: Install tar
           command: |
             yum -y install tar gzip
-            
+
       - run:
           name: Ensure back-end infrastructure exists
           command: |
@@ -375,6 +375,57 @@ jobs:
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
+  smoke-test:
+    docker:
+      - image: python:3.7-alpine3.11 
+    steps:
+      - Checkout
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update curl
+            pip install awscli
+      - run:
+          name: Backend smoke test
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --output text)
+            echo "------------------------------------"
+            echo BACKEND_URL: http://${BACKEND_IP}:3030/api/status
+            echo "------------------------------------"
+            if curl http://${BACKEND_IP}:3030/api/status | grep "ok"
+            then
+              echo "Backend Smoke Test Success"
+              exit 0
+            else
+              echo "Backend Smoke Test Failed"
+              exit 1
+            fi
+            
+      - run:
+          name: Frontend smoke test.
+          command: |
+            echo "------------------------------------"
+            echo http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/
+            echo "------------------------------------"
+
+            if curl -s http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/ | grep "Welcome"
+            then
+              echo "Frontend Smoke Test Success"
+              return 0
+            else
+              echo "Frontend Smoke Test Failed"
+              return 1
+            fi
+      
+      # Here's where you will add some code to rollback on failure 
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+          
 workflows:
   default:
     jobs:
